name: Snyk Infrastructure as Code
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '29 15 * * 6'
permissions:
  contents: read
jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run npm install
        run: npm install
      # Runs the Snyk code analysis
      - name: Run Snyk
        run: npm run snyk
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
